#!/usr/bin/env python3
"""Render an .xlsx sheet as a GitHub markdown table.

Stdlib only: the machine has no openpyxl, pandas or LibreOffice. Reads both
shared strings (what Excel writes) and inline strings (what a generator writes).
Only columns present in the header row are emitted, so notes parked in far
columns never reach the output.

Usage: xlsx_to_md.py IN.xlsx OUT.md [--title "..."] [--note "..."]

Interim tool. Once AD-4 lands, YAML becomes the source of truth and the
generator runs xlsx -> yaml instead, with this markdown view either dropped or
regenerated from the yaml.
"""
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from datetime import date

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

args = sys.argv[1:]
src, dst = args[0], args[1]
title = note = ""
for i, a in enumerate(args):
    if a == "--title":
        title = args[i + 1]
    if a == "--note":
        note = args[i + 1]

z = zipfile.ZipFile(src)
shared = []
if "xl/sharedStrings.xml" in z.namelist():
    shared = ["".join(t.text or "" for t in si.iter(f"{NS}t"))
              for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall(f"{NS}si")]

sheet_part = next(n for n in z.namelist() if n.startswith("xl/worksheets/sheet"))
ws = ET.fromstring(z.read(sheet_part))

rows = []
for row in ws.iter(f"{NS}row"):
    cells = {}
    for c in row.findall(f"{NS}c"):
        m = re.match(r"([A-Z]+)", c.get("r") or "A")
        col = m.group(1)
        v, isn = c.find(f"{NS}v"), c.find(f"{NS}is")
        # A formula cell carries both <f> and its cached <v>. Always take the cached
        # value: emitting the formula text would put "=LOWER(SUBSTITUTE(...))" into the
        # markdown instead of the result. Relevant if the slug column is a formula.
        if c.get("t") == "s" and v is not None and v.text:
            val = shared[int(v.text)]
        elif isn is not None:
            val = "".join(x.text or "" for x in isn.iter(f"{NS}t"))
        elif v is not None and v.text:
            val = v.text
        elif c.find(f"{NS}f") is not None:
            # Formula with no cached value: Excel has never evaluated it. Refuse to
            # guess, and make the gap visible rather than emitting an empty cell.
            val = "<uncached formula>"
        else:
            val = ""
        if val.strip():
            cells[col] = val.strip()
    if cells:
        rows.append(cells)

if not rows:
    sys.exit("no rows found")

# Header defines the emitted column set. Anything outside it is dropped.
header = rows[0]
cols = sorted(header, key=lambda s: (len(s), s))
data = rows[1:]


def cell(v):
    return v.replace("|", "\\|").replace("\n", " ")


out = []
if title:
    out.append(f"# {title}\n")
if note:
    out.append(f"{note}\n")
out.append("| " + " | ".join(cell(header[c]) for c in cols) + " |")
out.append("|" + "|".join("---" for _ in cols) + "|")
for r in data:
    out.append("| " + " | ".join(cell(r.get(c, "")) for c in cols) + " |")
out.append("")
out.append("<!--")
out.append(f"Version: GENERATED | Last Updated: {date.today().isoformat()} | Status: Draft")
out.append(f"Generated by xlsx_to_md.py from {src.split('/')[-1]}. Do not hand-edit.")
out.append("-->")

open(dst, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{dst}: {len(data)} data rows, {len(cols)} columns ({', '.join(header[c] for c in cols)})")
dropped = {c for r in rows for c in r} - set(cols)
if dropped:
    print(f"dropped columns outside the header range: {sorted(dropped)}")
